export const PERMISSIONS = {
  VIEW_PROJECT: 'view_project',
  CREATE_PROJECT: 'create_project',
  UPDATE_PROJECT: 'update_project',
  DELETE_PROJECT: 'delete_project',
  VIEW_TASK: 'view_task',
  CREATE_TASK: 'create_task',
  ASSIGN_TASK: 'assign_task',
  REASSIGN_TASK: 'reassign_task',
  UPDATE_TASK: 'update_task',
  DELETE_TASK: 'delete_task',
  VIEW_BOARD: 'view_board',
  MOVE_TASK: 'move_task',
  ADD_COMMENT: 'add_comment',
  REPLY_COMMENT: 'reply_comment',
  MANAGE_USERS: 'manage_users',
  MANAGE_ROLES: 'manage_roles',
  VIEW_AUDIT_LOG: 'view_audit_log',
  MANAGE_SETTINGS: 'manage_settings',
} as const;
