export const ROUTES = {
  LOGIN: '/login',
  SIGNUP: '/signup',
  ONBOARDING: '/onboarding',
  DASHBOARD: '/dashboard',
  PROJECTS: '/projects',
  PROJECT_CREATE: '/projects/create',
  PROJECT_DETAILS: '/projects/:id',
  TASKS: '/tasks',
  TASK_CREATE: '/tasks/create',
  TASK_DETAIL: '/tasks/:id',
  BOARD: '/board',
  USERS: '/users',
  ROLES: '/roles',
  ROLE_CREATE: '/roles/create',
  ROLE_EDIT: '/roles/:id/edit',
  SETTINGS: '/settings',
  PROFILE: '/settings/profile',
  AUDIT_LOG: '/settings/audit',
} as const;
