import type { User, Role, Project, Task, Comment, Activity, AuditLog } from '../types';

// ─── Users ───────────────────────────────────────────────────────────────────

export const mockUsers: User[] = [
  {
    id: 'user-1',
    name: 'Uday',
    email: 'uday@company.com',
    avatar: 'https://i.pravatar.cc/150?u=uday',
    status: 'active',
    lastLogin: '2026-08-21T08:15:00Z',
    createdAt: '2026-01-10T10:00:00Z',
  },
  {
    id: 'user-2',
    name: 'Priya',
    email: 'priya@company.com',
    avatar: 'https://i.pravatar.cc/150?u=priya',
    status: 'active',
    lastLogin: '2026-08-21T09:00:00Z',
    createdAt: '2026-02-15T10:00:00Z',
  },
  {
    id: 'user-3',
    name: 'Rahul',
    email: 'rahul@company.com',
    avatar: 'https://i.pravatar.cc/150?u=rahul',
    status: 'active',
    lastLogin: '2026-08-20T17:30:00Z',
    createdAt: '2026-03-01T10:00:00Z',
  },
  {
    id: 'user-4',
    name: 'Amit',
    email: 'amit@company.com',
    avatar: 'https://i.pravatar.cc/150?u=amit',
    status: 'active',
    lastLogin: '2026-08-21T07:45:00Z',
    createdAt: '2026-03-20T10:00:00Z',
  },
  {
    id: 'user-5',
    name: 'Neha',
    email: 'neha@company.com',
    avatar: 'https://i.pravatar.cc/150?u=neha',
    status: 'active',
    lastLogin: '2026-08-19T16:00:00Z',
    createdAt: '2026-04-05T10:00:00Z',
  },
];

// ─── Roles ───────────────────────────────────────────────────────────────────

export const mockRoles: Role[] = [
  {
    id: 'role-1',
    name: 'Admin',
    description: 'Full system access with all administrative permissions',
    permissions: [
      'projects.create',
      'projects.edit',
      'projects.delete',
      'projects.archive',
      'tasks.create',
      'tasks.edit',
      'tasks.delete',
      'tasks.assign',
      'users.create',
      'users.edit',
      'users.delete',
      'roles.manage',
      'audit.view',
      'settings.manage',
    ],
    isSystem: true,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'role-2',
    name: 'Project Manager',
    description: 'Can manage projects and tasks within assigned projects',
    permissions: [
      'projects.create',
      'projects.edit',
      'tasks.create',
      'tasks.edit',
      'tasks.delete',
      'tasks.assign',
      'users.view',
    ],
    isSystem: false,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'role-3',
    name: 'Developer',
    description: 'Can view projects and manage own tasks',
    permissions: [
      'projects.view',
      'tasks.view',
      'tasks.edit.own',
      'tasks.comment',
    ],
    isSystem: false,
    createdAt: '2026-01-01T00:00:00Z',
  },
];

// ─── Projects ────────────────────────────────────────────────────────────────

export const mockProjects: Project[] = [
  {
    id: 'proj-1',
    name: 'Knowledge Hub',
    description:
      'Internal knowledge management platform for documentation, wikis, and team collaboration. Centralizes company knowledge with search and tagging.',
    managerId: 'user-2',
    members: [
      { userId: 'user-1', roleId: 'role-1' },
      { userId: 'user-2', roleId: 'role-2' },
      { userId: 'user-3', roleId: 'role-3' },
      { userId: 'user-5', roleId: 'role-3' },
    ],
    statuses: [
      { id: 'ks-1', name: 'Started', color: '#94a3b8', order: 0, enabled: true },
      { id: 'ks-2', name: 'In Progress', color: '#3b82f6', order: 1, enabled: true },
      { id: 'ks-3', name: 'Testing', color: '#f59e0b', order: 2, enabled: true },
      { id: 'ks-4', name: 'Completed', color: '#22c55e', order: 3, enabled: true },
    ],
    startDate: '2026-07-01T00:00:00Z',
    endDate: '2026-09-30T00:00:00Z',
    status: 'active',
    createdAt: '2026-06-25T10:00:00Z',
  },
  {
    id: 'proj-2',
    name: 'CRM Platform',
    description:
      'Customer relationship management system for sales pipeline tracking, contact management, and reporting dashboards.',
    managerId: 'user-2',
    members: [
      { userId: 'user-1', roleId: 'role-1' },
      { userId: 'user-2', roleId: 'role-2' },
      { userId: 'user-4', roleId: 'role-3' },
      { userId: 'user-5', roleId: 'role-3' },
    ],
    statuses: [
      { id: 'cs-1', name: 'Planning', color: '#94a3b8', order: 0, enabled: true },
      { id: 'cs-2', name: 'Development', color: '#3b82f6', order: 1, enabled: true },
      { id: 'cs-3', name: 'Review', color: '#f59e0b', order: 2, enabled: true },
      { id: 'cs-4', name: 'Done', color: '#22c55e', order: 3, enabled: true },
    ],
    startDate: '2026-07-15T00:00:00Z',
    endDate: '2026-11-15T00:00:00Z',
    status: 'active',
    createdAt: '2026-07-10T10:00:00Z',
  },
  {
    id: 'proj-3',
    name: 'Website Redesign',
    description:
      'Complete redesign of the corporate website with modern UI/UX, responsive design, and improved performance metrics.',
    managerId: 'user-2',
    members: [
      { userId: 'user-1', roleId: 'role-1' },
      { userId: 'user-2', roleId: 'role-2' },
      { userId: 'user-3', roleId: 'role-3' },
      { userId: 'user-4', roleId: 'role-3' },
    ],
    statuses: [
      { id: 'ws-1', name: 'Design', color: '#a855f7', order: 0, enabled: true },
      { id: 'ws-2', name: 'Build', color: '#3b82f6', order: 1, enabled: true },
      { id: 'ws-3', name: 'Launch', color: '#f59e0b', order: 2, enabled: true },
      { id: 'ws-4', name: 'Complete', color: '#22c55e', order: 3, enabled: true },
    ],
    startDate: '2026-08-01T00:00:00Z',
    endDate: '2026-10-31T00:00:00Z',
    status: 'active',
    createdAt: '2026-07-28T10:00:00Z',
  },
];

// ─── Tasks ───────────────────────────────────────────────────────────────────

export const mockTasks: Task[] = [
  // Knowledge Hub (proj-1)
  {
    id: 'task-1',
    title: 'Set up project scaffolding with Vite and TypeScript',
    description:
      'Initialize the React project with Vite, configure TypeScript, ESLint, and Prettier. Set up folder structure for components, hooks, and utils.',
    projectId: 'proj-1',
    assignedTo: 'user-3',
    createdBy: 'user-2',
    priority: 'high',
    statusId: 'ks-4',
    startDate: '2026-07-01T00:00:00Z',
    dueDate: '2026-07-07T00:00:00Z',
    createdAt: '2026-07-01T08:00:00Z',
    updatedAt: '2026-07-06T16:30:00Z',
  },
  {
    id: 'task-2',
    title: 'Design database schema for articles and categories',
    description:
      'Create PostgreSQL schema with tables for articles, categories, tags, and user permissions. Include indexes for search performance.',
    projectId: 'proj-1',
    assignedTo: 'user-3',
    createdBy: 'user-2',
    priority: 'high',
    statusId: 'ks-4',
    startDate: '2026-07-08T00:00:00Z',
    dueDate: '2026-07-14T00:00:00Z',
    createdAt: '2026-07-07T09:00:00Z',
    updatedAt: '2026-07-13T17:00:00Z',
  },
  {
    id: 'task-3',
    title: 'Implement rich text editor for article creation',
    description:
      'Integrate TipTap editor with support for markdown, image uploads, code blocks, and table formatting.',
    projectId: 'proj-1',
    assignedTo: 'user-3',
    createdBy: 'user-2',
    priority: 'medium',
    statusId: 'ks-3',
    startDate: '2026-07-15T00:00:00Z',
    dueDate: '2026-08-10T00:00:00Z',
    createdAt: '2026-07-14T10:00:00Z',
    updatedAt: '2026-08-18T14:20:00Z',
  },
  {
    id: 'task-4',
    title: 'Build search and filtering API endpoints',
    description:
      'Create REST API endpoints for full-text search, tag filtering, and category-based article listing with pagination.',
    projectId: 'proj-1',
    assignedTo: 'user-5',
    createdBy: 'user-2',
    priority: 'medium',
    statusId: 'ks-2',
    startDate: '2026-08-01T00:00:00Z',
    dueDate: '2026-08-25T00:00:00Z',
    createdAt: '2026-07-28T11:00:00Z',
    updatedAt: '2026-08-15T09:45:00Z',
  },
  {
    id: 'task-5',
    title: 'Add role-based access control for content editing',
    description:
      'Implement permission checks so only authors and admins can edit articles. Add draft/publish workflow.',
    projectId: 'proj-1',
    assignedTo: 'user-5',
    createdBy: 'user-2',
    priority: 'low',
    statusId: 'ks-1',
    dueDate: '2026-09-15T00:00:00Z',
    createdAt: '2026-08-10T10:00:00Z',
    updatedAt: '2026-08-10T10:00:00Z',
  },

  // CRM Platform (proj-2)
  {
    id: 'task-6',
    title: 'Define API contract for contact management',
    description:
      'Document all REST endpoints for CRUD operations on contacts, companies, and deals. Use OpenAPI 3.0 spec.',
    projectId: 'proj-2',
    assignedTo: 'user-4',
    createdBy: 'user-2',
    priority: 'high',
    statusId: 'cs-4',
    startDate: '2026-07-15T00:00:00Z',
    dueDate: '2026-07-22T00:00:00Z',
    createdAt: '2026-07-15T08:00:00Z',
    updatedAt: '2026-07-21T17:00:00Z',
  },
  {
    id: 'task-7',
    title: 'Implement contact CRUD with validation',
    description:
      'Build the contact management module with form validation, duplicate detection, and activity logging.',
    projectId: 'proj-2',
    assignedTo: 'user-4',
    createdBy: 'user-2',
    priority: 'high',
    statusId: 'cs-2',
    startDate: '2026-07-23T00:00:00Z',
    dueDate: '2026-08-20T00:00:00Z',
    createdAt: '2026-07-22T09:00:00Z',
    updatedAt: '2026-08-19T16:30:00Z',
  },
  {
    id: 'task-8',
    title: 'Build sales pipeline Kanban board',
    description:
      'Drag-and-drop Kanban interface for tracking deals through pipeline stages. Show deal value, contact info, and activity timeline.',
    projectId: 'proj-2',
    assignedTo: 'user-4',
    createdBy: 'user-2',
    priority: 'medium',
    statusId: 'cs-2',
    startDate: '2026-08-10T00:00:00Z',
    dueDate: '2026-09-05T00:00:00Z',
    createdAt: '2026-08-05T10:00:00Z',
    updatedAt: '2026-08-20T11:00:00Z',
  },
  {
    id: 'task-9',
    title: 'Create reporting dashboard with charts',
    description:
      'Build analytics dashboard showing revenue by month, pipeline conversion rates, team performance, and activity summaries using Recharts.',
    projectId: 'proj-2',
    assignedTo: 'user-5',
    createdBy: 'user-2',
    priority: 'low',
    statusId: 'cs-1',
    dueDate: '2026-10-15T00:00:00Z',
    createdAt: '2026-08-12T10:00:00Z',
    updatedAt: '2026-08-12T10:00:00Z',
  },
  {
    id: 'task-10',
    title: 'Set up email notification system',
    description:
      'Integrate email service for deal stage changes, task assignments, and follow-up reminders. Support both SMTP and API providers.',
    projectId: 'proj-2',
    assignedTo: 'user-5',
    createdBy: 'user-2',
    priority: 'medium',
    statusId: 'cs-1',
    dueDate: '2026-10-30T00:00:00Z',
    createdAt: '2026-08-15T10:00:00Z',
    updatedAt: '2026-08-15T10:00:00Z',
  },

  // Website Redesign (proj-3)
  {
    id: 'task-11',
    title: 'Create wireframes for homepage and about page',
    description:
      'Design low-fidelity wireframes in Figma for the main landing pages. Include mobile responsive variants.',
    projectId: 'proj-3',
    assignedTo: 'user-3',
    createdBy: 'user-2',
    priority: 'high',
    statusId: 'ws-4',
    startDate: '2026-08-01T00:00:00Z',
    dueDate: '2026-08-07T00:00:00Z',
    createdAt: '2026-08-01T08:00:00Z',
    updatedAt: '2026-08-06T17:30:00Z',
  },
  {
    id: 'task-12',
    title: 'Develop design system and component library',
    description:
      'Build reusable React components (buttons, cards, modals, navigation) following the new brand guidelines. Document with Storybook.',
    projectId: 'proj-3',
    assignedTo: 'user-3',
    createdBy: 'user-2',
    priority: 'high',
    statusId: 'ws-2',
    startDate: '2026-08-08T00:00:00Z',
    dueDate: '2026-08-28T00:00:00Z',
    createdAt: '2026-08-07T09:00:00Z',
    updatedAt: '2026-08-20T15:00:00Z',
  },
  {
    id: 'task-13',
    title: 'Implement responsive navigation with mega menu',
    description:
      'Build the site-wide navigation with mega menu dropdowns, mobile hamburger menu, and search integration.',
    projectId: 'proj-3',
    assignedTo: 'user-4',
    createdBy: 'user-2',
    priority: 'medium',
    statusId: 'ws-2',
    startDate: '2026-08-15T00:00:00Z',
    dueDate: '2026-09-01T00:00:00Z',
    createdAt: '2026-08-12T10:00:00Z',
    updatedAt: '2026-08-19T14:00:00Z',
  },
  {
    id: 'task-14',
    title: 'Optimize Core Web Vitals and Lighthouse scores',
    description:
      'Achieve Lighthouse score of 90+ across all metrics. Implement lazy loading, image optimization, and code splitting.',
    projectId: 'proj-3',
    assignedTo: 'user-3',
    createdBy: 'user-2',
    priority: 'low',
    statusId: 'ws-1',
    dueDate: '2026-10-15T00:00:00Z',
    createdAt: '2026-08-18T10:00:00Z',
    updatedAt: '2026-08-18T10:00:00Z',
  },
  {
    id: 'task-15',
    title: 'Set up CI/CD pipeline for staging and production',
    description:
      'Configure GitHub Actions for automated testing, building, and deployment. Set up preview deployments for PRs.',
    projectId: 'proj-3',
    assignedTo: 'user-4',
    createdBy: 'user-2',
    priority: 'medium',
    statusId: 'ws-1',
    dueDate: '2026-10-20T00:00:00Z',
    createdAt: '2026-08-19T10:00:00Z',
    updatedAt: '2026-08-19T10:00:00Z',
  },
];

// ─── Comments ────────────────────────────────────────────────────────────────

export const mockComments: Comment[] = [
  {
    id: 'comment-1',
    taskId: 'task-3',
    userId: 'user-3',
    content:
      'I have started integrating TipTap. The basic editor is working but image upload needs more work.',
    createdAt: '2026-08-12T10:00:00Z',
  },
  {
    id: 'comment-2',
    taskId: 'task-3',
    userId: 'user-2',
    content:
      'Great progress! Can you also add support for embedding videos from YouTube and Vimeo?',
    parentId: 'comment-1',
    createdAt: '2026-08-12T11:30:00Z',
  },
  {
    id: 'comment-3',
    taskId: 'task-3',
    userId: 'user-3',
    content:
      'Sure, I will add oEmbed support. Should have it ready by end of week.',
    parentId: 'comment-2',
    createdAt: '2026-08-12T14:00:00Z',
  },
  {
    id: 'comment-4',
    taskId: 'task-7',
    userId: 'user-4',
    content:
      'Contact CRUD is complete. Form validation includes email format, phone number, and required fields.',
    createdAt: '2026-08-15T09:00:00Z',
  },
  {
    id: 'comment-5',
    taskId: 'task-7',
    userId: 'user-2',
    content:
      'Looks good. Please also add duplicate detection based on email address before saving.',
    parentId: 'comment-4',
    createdAt: '2026-08-15T10:15:00Z',
  },
  {
    id: 'comment-6',
    taskId: 'task-8',
    userId: 'user-4',
    content:
      'The drag and drop is working with @dnd-kit. Still need to add optimistic updates for a smoother experience.',
    createdAt: '2026-08-18T11:00:00Z',
  },
  {
    id: 'comment-7',
    taskId: 'task-12',
    userId: 'user-3',
    content:
      'Finished the button and input components. Moving on to the modal and dropdown menus next.',
    createdAt: '2026-08-19T09:30:00Z',
  },
  {
    id: 'comment-8',
    taskId: 'task-12',
    userId: 'user-2',
    content:
      'Make sure all components have proper TypeScript props interfaces and support dark mode.',
    parentId: 'comment-7',
    createdAt: '2026-08-19T10:00:00Z',
  },
  {
    id: 'comment-9',
    taskId: 'task-4',
    userId: 'user-5',
    content:
      'Search endpoint is live with full-text search using PostgreSQL ts_vector. Tag filtering is also done.',
    createdAt: '2026-08-16T14:00:00Z',
  },
  {
    id: 'comment-10',
    taskId: 'task-13',
    userId: 'user-4',
    content:
      'Navigation component is responsive. Mega menu works on desktop, hamburger on mobile. Need to finalize the search overlay.',
    createdAt: '2026-08-20T11:00:00Z',
  },
];

// ─── Activities ──────────────────────────────────────────────────────────────

export const mockActivities: Activity[] = [
  {
    id: 'act-1',
    userId: 'user-3',
    action: 'completed',
    entity: 'task',
    entityId: 'task-1',
    entityName: 'Set up project scaffolding with Vite and TypeScript',
    previousValue: 'ks-2',
    newValue: 'ks-4',
    createdAt: '2026-08-10T09:00:00Z',
  },
  {
    id: 'act-2',
    userId: 'user-2',
    action: 'created',
    entity: 'task',
    entityId: 'task-14',
    entityName: 'Optimize Core Web Vitals and Lighthouse scores',
    createdAt: '2026-08-18T10:00:00Z',
  },
  {
    id: 'act-3',
    userId: 'user-4',
    action: 'updated',
    entity: 'task',
    entityId: 'task-8',
    entityName: 'Build sales pipeline Kanban board',
    previousValue: 'cs-1',
    newValue: 'cs-2',
    createdAt: '2026-08-20T11:00:00Z',
  },
  {
    id: 'act-4',
    userId: 'user-5',
    action: 'commented',
    entity: 'task',
    entityId: 'task-4',
    entityName: 'Build search and filtering API endpoints',
    createdAt: '2026-08-16T14:00:00Z',
  },
  {
    id: 'act-5',
    userId: 'user-2',
    action: 'assigned',
    entity: 'task',
    entityId: 'task-15',
    entityName: 'Set up CI/CD pipeline for staging and production',
    previousValue: undefined,
    newValue: 'user-4',
    createdAt: '2026-08-19T10:00:00Z',
  },
];

// ─── Audit Logs ──────────────────────────────────────────────────────────────

export const mockAuditLogs: AuditLog[] = [
  {
    id: 'audit-1',
    userId: 'user-1',
    action: 'created',
    module: 'projects',
    record: 'proj-3',
    newValue: 'Website Redesign',
    createdAt: '2026-07-28T10:00:00Z',
  },
  {
    id: 'audit-2',
    userId: 'user-2',
    action: 'updated',
    module: 'projects',
    record: 'proj-1',
    previousValue: 'ks-1',
    newValue: 'ks-2',
    createdAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'audit-3',
    userId: 'user-2',
    action: 'assigned',
    module: 'tasks',
    record: 'task-4',
    previousValue: undefined,
    newValue: 'user-5',
    createdAt: '2026-07-28T11:00:00Z',
  },
  {
    id: 'audit-4',
    userId: 'user-3',
    action: 'completed',
    module: 'tasks',
    record: 'task-1',
    previousValue: 'ks-2',
    newValue: 'ks-4',
    createdAt: '2026-07-06T16:30:00Z',
  },
  {
    id: 'audit-5',
    userId: 'user-4',
    action: 'completed',
    module: 'tasks',
    record: 'task-6',
    previousValue: 'cs-2',
    newValue: 'cs-4',
    createdAt: '2026-07-21T17:00:00Z',
  },
  {
    id: 'audit-6',
    userId: 'user-2',
    action: 'created',
    module: 'users',
    record: 'user-5',
    newValue: 'Neha',
    createdAt: '2026-04-05T10:00:00Z',
  },
  {
    id: 'audit-7',
    userId: 'user-1',
    action: 'updated',
    module: 'roles',
    record: 'role-3',
    previousValue: 'projects.view, tasks.view',
    newValue: 'projects.view, tasks.view, tasks.edit.own, tasks.comment',
    createdAt: '2026-03-15T10:00:00Z',
  },
  {
    id: 'audit-8',
    userId: 'user-2',
    action: 'updated',
    module: 'projects',
    record: 'proj-2',
    previousValue: 'Planning',
    newValue: 'Development',
    createdAt: '2026-08-05T09:00:00Z',
  },
  {
    id: 'audit-9',
    userId: 'user-4',
    action: 'updated',
    module: 'tasks',
    record: 'task-8',
    previousValue: 'cs-1',
    newValue: 'cs-2',
    createdAt: '2026-08-20T11:00:00Z',
  },
  {
    id: 'audit-10',
    userId: 'user-1',
    action: 'archived',
    module: 'projects',
    record: 'proj-old',
    previousValue: 'active',
    newValue: 'archived',
    createdAt: '2026-06-01T10:00:00Z',
  },
];
